# Generated by Django 4.2 on 2023-05-29 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='searchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('flipkart_title', models.CharField(max_length=200)),
                ('flipkart_price', models.CharField(max_length=100)),
                ('amazon_title', models.CharField(max_length=200)),
                ('amazon_price', models.CharField(max_length=100)),
                ('croma_title', models.CharField(max_length=200)),
                ('croma_price', models.CharField(max_length=100)),
                ('gadget_title', models.CharField(max_length=200)),
                ('gadget_price', models.CharField(max_length=100)),
                ('tata_title', models.CharField(max_length=200)),
                ('tata_price', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrackHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=300)),
                ('user_price', models.IntegerField()),
                ('user_email', models.EmailField(max_length=254)),
                ('website', models.TextField(max_length=50)),
                ('status', models.TextField(max_length=50)),
            ],
        ),
    ]
